### ISSUE TITLE
Unexpected space usage with nested ZipSink and -O

### ISSUE THREAD

**Issue by mkscrg** [snoyberg/conduit#197]
*Runnable version in a Gist here: <https://gist.github.com/mkscrg/3ed1d29df38169a8f4e3>*

Conduit is awesome! We use it in a few places, most critically for processing streams of rows of tabular data. The code in this example is motivated by that usage.

```haskell
-- Sink.hs

type Row = [Maybe Int]
type ColResult = (Int, Bool)
type ColDesc = ()

-- compute a result for each column, driven by a list of column descriptors
rowS :: Monad m => [ColDesc] -> Sink Row m [ColResult]
rowS descs = sequenceSinks $ zipWith colS [0 ..] descs
  where
    colS i d = CL.map (!! i) =$ columnS d

columnS :: Monad m => ColDesc -> Sink (Maybe Int) m ColResult
columnS _ = CL.catMaybes =$ zipSinks countS positiveS
```

(See [the gist](https://gist.github.com/mkscrg/3ed1d29df38169a8f4e3#file-sink-hs-L24-L31) for `zipSinks`, `countS`, and `positiveS`.)

`rowS` is connected to a source and run:

```haskell
-- Main.hs

main :: IO ()
main = do
    _ <- CL.sourceList (repeat [Just 5, Nothing]) $$ rowS [(), ()]
    return ()
```

(Note that `main` and `rowS` are in separate files.)

Compiled without optimization, this runs in constant space (measured by [polling `ps`](https://gist.github.com/mkscrg/3ed1d29df38169a8f4e3#file-run-L22-L26)):

```shell
$ ./run
[1 of 2] Compiling Sink             ( Sink.hs, Sink.o )
[2 of 2] Compiling Main             ( Main.hs, Main.o )
Linking Main ...
0       780
1       2208
2       2208
3       2208
```

But when compiled with `-O` or `-O2`, it performs badly:

```shell
$ ./run -O
[1 of 2] Compiling Sink             ( Sink.hs, Sink.o )
[2 of 2] Compiling Main             ( Main.hs, Main.o )
Linking Main ...
0       836
1       184840
2       356784
3       537096
```

Interestingly, all of the following "fix" the problem:

- Adding a `NOINLINE` pragma to `columnS`. This is our solution in practice   today.
- Moving all of `Sink.hs` into `Main.hs`.
- Compiling with `-fno-full-laziness`, passed to GHC directly or via   `OPTIONS_GHC` in `Sink.hs`.
- With some versions of this code (not this one, apologies), enabling   profiling via `-prof -fprof-auto` masks the issue. That's true of   our "real" implementation, and it made this a lot harder to track down!

Is this a GHC problem, a conduit problem, or user error?

**Comment by snoyberg** [comment]
I haven't dived into this exact case yet, but generally speaking there are many tradeoffs in GHC between keeping CAFs in memory and recomputing them on each usage. Everything you've said here implies that's the issue, since the behavior is affected by inlining, module placement, and optimizations. I won't have a chance to look at this until next week, but the next step would be to look at the core and see what exactly is happening.

There have been some mailing list threads, GHC trac tickets, and conversations at conferences about this kind of problem (I discussed almost this exact issue with Simon PJ at ICFP last year). I'm guessing this falls into the category of "maybe GHC problem, but GHC may have its reasons for doing it." In which case: using a workaround like explicitly turning off inlining may be the best approach (plus, filing a GHC trac issue about the problem).

**Comment by snoyberg** [comment]
I've looked at the core for this a bit, and nothing in particular is jumping out at me. I would suggest opening a GHC trac ticket on this.

**Comment by snoyberg** [comment]
Closing as an upstream issue.
