### ISSUE TITLE
zipping the outputs of conduits

### ISSUE THREAD

**Issue by kaizhang** [snoyberg/conduit#273]
There are 3 different wrappers for doing different kinds of zipping. But I cannot find any function allowing me to do this:

`sequenceConduits' :: (Traversable f, Monad m) => f (ConduitM i o m ()) -> ConduitM i (f o) m ()`

**Comment by snoyberg** [comment]
It doesn't exist today, and that's by design. When it comes to multiple `Conduit`s, there's no way to guarantee that all of them will produce output at the same rate. For example, with `[c1, c2]`, it's possible that for a given input `c1` will produce no output and `c2` will produce thousands of outputs.

**Comment by kaizhang** [comment]
But this is also true when combining multiple sources, where the solution is "A combined source will take input yielded from each of its Sources until any of them stop producing output." Why can't we adapt the same approach?

**Comment by snoyberg** [comment]
Because there's no need to do buffering of input or output in the case of a
source.
