### ISSUE TITLE
Why does MonadResource require MonadIO *and* MonadBase IO?

### ISSUE THREAD

**Issue by ocharles** [snoyberg/conduit#294]
The two constraints are operationally equivalent (no?), so why do we require both of them? This ends up infecting the signatures of anything that uses `runResourceT`, because

```haskell
(MonadThrow m, MonadBase IO m, MonadIO m, Applicative m) => MonadResource (ResourceT m)
```

There is in fact even more redundancy in this signature - `Applicative m` is a given because all of the three prior constraints require `Monad m`. That isn't such a problem, because if I'm on a recent GHC that doesn't get propagated because GHC can see it's superfluous.

**Comment by ocharles** [comment]
Also, why bother with `MonadThrow`, when you could just as well write `liftBase . throwIO` (or `liftIO . throwIO`)? The only base instances for `MonadThrow` are for `Q`, `STM`, `[]`, `Maybe` and `IO` - everything else just (and has to) proxies down to the base layer - which we already know is `IO`.

**Comment by snoyberg** [comment]
1. It's a question of conveniences: do we want a `MonadResource` context to automatically imply the others, or not? The fact is that `MonadBase IO` is necessary because of how `runResourceT` is implemented\*, and `MonadIO` is just a more commonly used version of that constraint. It would lead to a lot of confusion IMO if `liftIO` didn't _just work_.
2. `MonadThrow` is a bit trickier, but basically someone could add in a transformer in the stack which intercepts the `throwM` calls. Personally, I think that's a terrible mistake, but providing the `MonadThrow` instance allows resourcet machinery to send exceptions to that layer if desired by the user.

\* OK, it's not _technically_ necessary, but the constraint will be fulfilled in all cases I can think of because of the constraints on `runResourceT`.

**Comment by ocharles** [comment]
Ok, I'm not entirely following why that means these need to be in the class context rather than just the function contexts, but this answers my questions. Thanks!

**Comment by snoyberg** [comment]
No problem. The try and clarify a bit more: there's absolutely zero requirement that the class context itself have these constraints, in the same way that there's zero requirement that `Applicative` be a superclass of `Monad`. However, at usage sites, it's easier to be able to simply state `Monad m` and have the `Applicative m` be implied. Similar logic applies here too.

(And my comments about `MonadThrow` and the extra layer getting the right exception are probably bogus I just realized, since the `liftResourceT` will hide that all away. It's just another case of "this should always be a superclass, so let's make it easier to access it.)
