### ISSUE TITLE
streamingProcess and stdin buffering

### ISSUE THREAD

**Issue by CthulhuDen** [snoyberg/conduit#334]
With default Handle buffering mode it's not possible to interact with programs because input gets buffered.

This may seem like an issue with `streaming-commons`, but it's only an issue when using Conduit as input sink for a new process, because then we have no access to underlying handle and so cannot change buffering mode.

**Comment by CthulhuDen** [comment]
This was probably a collateral damage from fixing https://github.com/snoyberg/conduit/issues/322.

**Comment by snoyberg** [comment]
Shoot, this looks like a "damned if you do, damned if you don't" situation. I have a few different thoughts on how to address this.

1. Instead of getting a `Sink`, just ask for the raw `Handle`, modify it as desired, and then use `sinkHandle`. That should work immediately, though it's not as elegant from a user perspective.
2. This requires a breaking change and losing some niceness around type inference. The idea is to allow for a `Flush ByteString` and `Builder` instance for `InputSource`. Then you'd be able to `yield Flush` to force flushing.
3. Add some special logic to treat `yield B.empty` as a command to flush.
4. Add some newtypes to state explicitly that you want the stream to have different buffering strategies.

Do you have any thoughts on these options?

**Comment by CthulhuDen** [comment]
Only issue with your proposed addition is I think it need third constructor which will pass chunk and flush, so that user can just plug 'mapC FlushChunk` or something before the sink.

Actually, I think it's generally a good idea to flush immediately into process stdin, so I was thinking about making this default behaviour, and maybe add Newtype to override. Currently, I use the following newtype as a workaround, but it could be done in reverse:

```haskell
newtype FlushingSink o m = Flushing (ConduitM BS.ByteString o m ())

sinkFlushingHandle :: MonadIO m => Handle -> ConduitM BS.ByteString o m ()
sinkFlushingHandle h = awaitForever $ \bs -> liftIO $ BS.hPut h bs >> hFlush h

instance MonadIO m => InputSource (FlushingSink o m) where
  isStdStream = (\(Just h) -> return $ Flushing $ sinkFlushingHandle h, Just CreatePipe)

instance (MonadIO m, MonadIO n) => InputSource (FlushingSink o m, n ()) where
  isStdStream = (\(Just h) -> return (Flushing $ sinkFlushingHandle h, liftIO $ hClose h), Just CreatePipe)
```

**Comment by CthulhuDen** [comment]
Of course, ability to manually flush could be useful as well, maybe as another newtype. This way there needs not to be any BC (if the keep current as default), or only minor BC (if we would make flushing after each chunk default).

**Comment by snoyberg** [comment]
I don't believe the default usage of this library is for interactive user processes, but for batch processing. Keeping the defaults optimized for that use case makes sense to me.

**Comment by CthulhuDen** [comment]
Absolutely. Then, option 4 seems reasonable and most convenient, one newtype for accepting Flush commands from upstream and another for Flush after every chunk.

**Comment by snoyberg** [comment]
You interested in sending a PR for the newtype you'd like?

**Comment by CthulhuDen** [comment]
Sure! However, some questions first: do you think Flush sink (like one in your code) should be done as you did (with BC break) or as one of newtypes? And also, do we need builder instance in this RP, as it seems not so much related?

**Comment by snoyberg** [comment]
I'd prefer the newtype. The reason I played with the Builder approach is because it automatically gives you what you're looking for: you can insert a flush command into the stream as a Builder and then get the interactivity you want automatically. In many ways it may be better to _only_ have the Builder interface and avoid the Flush approach entirely. I'm in favor of adding both newtypes.

**Comment by ony** [comment]
It looks like [`FlushInput`](http://hackage.haskell.org/package/conduit-extra-1.3.1.1/docs/src/Data.Conduit.Process.html#FlushInput) is already in `Data.Conduit.Process` module. It looks quiet natural for me to write:

```haskell
((FlushInput sink, close), source, ClosedStream, cph)
                <- streamingProcess (shell cmd)
```

Is there any reason why since 1.2.2 feature is there, but not exposed?

**Comment by snoyberg** [comment]
Looks like it was accidental that it wasn't exported. Want to send a PR to add the exports?
