### ISSUE TITLE
Drop finalizers from the library?

### ISSUE THREAD

**Issue by snoyberg** [snoyberg/conduit#343]
See explanation in https://www.snoyman.com/blog/2018/01/drop-conduits-finalizers

**Comment by luispedro** [comment]
Besides the maintenance burden, is there a run-time cost to having finalizers? Any timings?

With finalizers, the finalizers are most often built and never used (most of the time, they're `return ()` too). Perhaps, in the end, it doesn't matter; but it should add some GC overhead.

**Comment by snoyberg** [comment]
I have absolutely no performance numbers to bring to the table on this, but I suspect your analysis is spot on.

**Comment by jdreaver** [comment]
(I originally posted this on Reddit but I realized you may not be monitoring that thread)

I'm currently using a finalizer to measure the execution time of a `Conduit` from `persistent`. In particular, I am overriding the `stmtQuery` of every `persistent` `Statement` so I can record the execution end time and then send the info off to AWS X-Ray. It looks a bit like this:

```haskell
stmtQuery'
  :: forall m. MonadIO m
  => Statement
  -> Text
  -> [PersistValue]
  -> Acquire (Source m [PersistValue])
stmtQuery' statement sql vals = do
  -- Start timer and create Source
  startTime <- liftIO getPOSIXTime
  source <- stmtQuery statement vals

  -- Add a finalizer to the Source that will send the trace
  pure $ addCleanup (\_ -> liftIO $ sendQueryTrace startTime ...) source
```

Is there a way I could replace this with just another `Conduit` component and slap it on the end with `.|`? I was worried that wouldn't work because I want to know when the final consumer of this `Source` is done with the whole thing, and if I just add an intermediate stage I won't get the proper timing (or do all parts of the conduit tend to complete at once?).

This is also a peculiar situation I admit. I'm mostly using this as a hook to get query timing out of `persistent` instead of having to override every single function that uses this `Source`. If you have any ways I could accurately record how long it takes our queries to run and stream results back into Haskell that would be neato.

(Fun fact: using this method of recording query times, we realized we have lots of queries that finish executing in only 1 ms on our postgres DB, but we realize the results have so much data it takes almost 100ms to stream it back! That is to say this is super useful to have.)

**Comment by snoyberg** [comment]
Copying my response to @jdreaver from Reddit (https://www.reddit.com/r/haskell/comments/7nuyk8/drop_conduits_finalizers/ds4sssz/)

This is a great example. What I believe would work is changing your type signature to:

    Acquire ((Source m [PersistValue] -> m a) -> m a)

And the implementation would look like:

    pure $ \inner -> do
        startTime <- liftIO getPOSIXTime
        res <- inner source
        liftIO $ sendQueryTrace startTime ...
        return res

Obviously not typed-checked :)

**Comment by jdreaver** [comment]
Hmm, I'm not quite sure that would work. I'm using `stmtQuery'` to override [`stmtQuery`](https://hackage.haskell.org/package/persistent-2.7.3/docs/Database-Persist-Sql.html#v:stmtQuery), which needs to return `Acquire (Source m [PersistValue])`. I have to dig in and think about it though haha. I made this a few weeks ago and I forgot the nuts and bolts.

I wouldn't let an example like this count against your proposal though. This use case seems very specialized and it only exists because `persistent` doesn't provide any sort of hooks around query execution. I'm sure most users of `conduit` have control over their `Sink` and could add timing there.

**Comment by luispedro** [comment]
Here's one use case that is probably hard to do without finalizers (I was actually writing code that uses this library and realized that it _must use finalizers_; so I checked the code and indeed, it does).

https://www.stackage.org/haddock/lts-10.2/stm-conduit-3.0.0/Data-Conduit-TMChan.html#v:sourceTMChan

    sourceTMChan :: MonadIO m => TMChan a -> Source m a

`TMChan` is a transactional channel. This reads from the channel until there is no more data, but will close it if downstream finishes early. Not closing the channel can lead to runaway threads, MVar errors, all sorts of nasty case

**Comment by snoyberg** [comment]
I've got worse news for you then: that code isn't exception safe, and can end up leaving the `TMChan` open indefinitely. At the very least, it would need to have a `MonadResource` constraint, which will guarantee that it's closed, but won't guarantee promptness. To get promptness, you'd need to change the type signature:

```haskell
withSourceTMChan :: (MonadResource m, MonadIO n) => TMChan a -> (Source n a -> m b) -> m b
withSourceTMChan chan inner = do
  key <- register $ liftIO $ atomically $ closeTMChan chan
  res <- inner $ chanToSource chan
  release key
  return res
```

**Comment by luispedro** [comment]
Yep, that's true.

**Comment by snoyberg** [comment]
This was included in conduit 1.3.

**Comment by snoyberg** [comment]
Just use the bracket pattern:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-12.9 script

import           Conduit
import           Control.Monad (forever)
import           Control.Monad.Trans.Resource (allocate, release)
import           Data.Conduit.Binary (sourceFile)
import           Data.Foldable (for_)
import qualified System.IO as IO

readFileLinesSource
  :: String
  -> FilePath
  -> (ConduitT () String (ResourceT IO) () -> ConduitT () String (ResourceT IO) a)
  -> ConduitT () String (ResourceT IO) a
readFileLinesSource name file inner = do
  (key, h) <- allocate
    (do h <- IO.openFile file IO.ReadMode
        putStrLn $ "{" ++ name ++ ": " ++ file ++ " open}"
        return h )
    (\h -> do
        IO.hClose h
        putStrLn $ "{" ++ name ++ ": " ++ file ++ " closed}" )
  a <- inner $ fromHandle h
  release key
  return a
  where
    fromHandle h = forever $ liftIO (IO.hGetLine h) >>= yield

writeFileLinesSink :: FilePath -> ConduitT String void (ResourceT IO) ()
writeFileLinesSink file = bracketP
    (do h <- IO.openFile file IO.WriteMode
        putStrLn $ "{" ++ file ++ " open for writing}"
        return h )
    (\h -> do
        IO.hClose h
        putStrLn $ "{" ++ file ++ " closed for writing}" )
    fromHandle
  where
    fromHandle h = awaitForever $ \line -> do
        liftIO (IO.hPutStrLn h line)

producer :: ConduitT () String (ResourceT IO) ()
producer = do
    for_ [1..2000] $ \i -> do
        let name = show i
        readFileLinesSource name "input.txt" $ \src -> src .| takeC 2
    liftIO $ putStrLn "Some long running computation"

main :: IO ()
main = runConduitRes $ producer .| writeFileLinesSink "output.txt"
```

Exercise to the reader: apply bracket pattern to `writeFileLinesSink` as well :)

**Comment by nh2** [comment]
Great, thanks! I extracted a `bracketResource` like this:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-12.9 script

import           Conduit
import           Control.Monad (forever)
import           Control.Monad.Trans.Resource (allocate, release)
import           Data.Conduit.Binary (sourceFile)
import           Data.Foldable (for_)
import qualified System.IO as IO

bracketResource ::
    (MonadResource m)
    => IO a -- ^ allocate
    -> (a -> IO ()) -- ^ release
    -> (a -> m b) -- ^ what to do with the allocated resource
    -> m b
bracketResource a fr inner = do
    (key, x) <- allocate a fr
    res <- inner x
    release key
    return res

withReadFileLinesSource ::
    (MonadResource m)
    => String
    -> FilePath
    -> (ConduitT () String (m) () -> ConduitT () String (m) a)
    -> ConduitT () String (m) a
withReadFileLinesSource name file inner = do
    bracketResource
        (do h <- IO.openFile file IO.ReadMode
            putStrLn $ "{" ++ name ++ ": " ++ file ++ " open}"
            return h )
        (\h -> do
            IO.hClose h
            putStrLn $ "{" ++ name ++ ": " ++ file ++ " closed}" )
        (\h -> inner $ do
            forever $ liftIO (IO.hGetLine h) >>= yield)

withWriteFileLinesSink ::
    (MonadResource m)
    => FilePath
    -> (ConduitT String void m () -> ConduitT i o m a)
    -> ConduitT i o m a
withWriteFileLinesSink file inner =
    bracketResource
        (do h <- IO.openFile file IO.WriteMode
            putStrLn $ "{" ++ file ++ " open for writing}"
            return h )
        (\h -> do
            IO.hClose h
            putStrLn $ "{" ++ file ++ " closed for writing}" )
        (\h -> inner $ do
            awaitForever $ \line -> do
                liftIO (IO.hPutStrLn h line))

writeFileLinesSink :: (MonadResource m) => FilePath -> ConduitT String void m ()
writeFileLinesSink file = withWriteFileLinesSink file id

producer :: (MonadResource m) => ConduitT () String m ()
producer = do
    for_ [1..2000] $ \i -> do
        let name = show i
        withReadFileLinesSource name "input.txt" $ \src -> src .| takeC 2
    liftIO $ putStrLn "Some long running computation"

main :: IO ()
main = do
    -- Sink with full ResourceT lifetime:
    runConduitRes $ producer .| writeFileLinesSink "output.txt"
    -- Sink with bracketed lifetime:
    runConduitRes $ withWriteFileLinesSink "output.txt" (\sink -> producer .| sink)
```

**Comment by maxigit** [comment]
I'm trying to upgrage to Yesod 1.6 and I'm stuck with a problem related to the absence of `addCleanUp`.
I managed to simplify the problem which seems to not work as expected.
I create a temporary file (using either `withTempFile` or `openTempFile`) in a Yesod Handler and try to send it as a response using either `sendFile` or `sendSource`. In each case, I send a empty file, as if the temporay file was closed or deleted before the file was sent. My code use to work perfectly before using `addCleanUp` and I have been able to find a way to execute the desired AFTER the response has been made, as it seems to work with `addCleanUp` (which I'm not sure why it worked either).

I'm pretty sure there is obvious workaround.

**Comment by snoyberg** [comment]
Sorry, it's hard for me to picture what this could would look like here. Maybe adding a more explicit `hClose` will force the buffer to be flushed to the disk?

**Comment by maxigit** [comment]
I already close the hanlde using `hClose`. Basically I'm trying to do something along the line 

    generateLabelsResponse ::
      Text
      -> Text
      -> ConduitT () Text Handler ()
      -> Handler TypedContent
    generateLabelsResponse outputName template labelSource =
      withAcquire (mkAcquire (openTempFile "/tmp" (unpack outputName))
                  (\ (tmp, handle) -> hClose handle >> removeFile tmp) 
                  ) $ \(tmp, thandle) -> do
      withSystemTempFile "input" $ \inputPath ihandle -> do
      -- save csv so glabels can read it
      runConduit $ labelSource .| encodeUtf8C .| sinkHandle ihandle
      (ClosedStream, ClosedStream, Inherited, processHandle ) <- streamingProcess (proc "glabels-3-batch"
                                                              ["--input"
                                                              , inputPath
                                                              , "--output"
                                                              , tmp
                                                              , (unpack template)
                                                              ]
                                                        ) {env = Just [("LANG", "C.UTF-8")]}
      _exitCode <- waitForStreamingProcess processHandle
      setAttachment (fromStrict outputName)
      sendFile "application/pdf" tmp

I just called a process to write in a tempory file and send it using `sendFile`. 
The problem is to remove the file. The actuall code calls  `hClose handle >> removeFile tmp` in the finalizer (using `withAcquire`) and send 0 bytes, as the file is removed before the respond is sent.
If I remove the `removeFile` bit, evirything works fine (except I get stuck with a temporay file).
Anyway the question boils done to , how to execute a bit code after the response has been sent.
I though `Acquire` and `ResourceT` was the solution but it seems that the finalizer are called straight away. 

I can leave my extra temporary file, but the code use to work the way I wanted using `addCleanUp`. 
I thought you were interested in example of `addCleanUp` being needed, so there we go ;-)

**Comment by snoyberg** [comment]
It's hard to see how this is an example of wanting `addCleanup`. I'm probably just not understanding correctly. But broader question: you're using `withSystemTempFile` for opening the `input` file, why not use the same for opening the output file?

**Comment by maxigit** [comment]
I'll answer the two questions in reverse order.
I'm not using `withSystemTempFile` with the output file because it does NOT work.
The temporary file is deleted before `sendFile` has the time to use it. 
I agree withSystemTempFile and my use of `withAcquire` should be equivalent and they are : they don't work.
Initially, i tried `withSystemTempFile`, didn't work, then tried `withAcquire`, which only worke if I remove the `removeFile` (meaning I'm not actually cleaning anything).

For the first question, here is the original code  which `addCleanUp`. The main difference is before, instead of "sinking" the conduit to an input file. I would sink the conduit to the stdin of the process and get `glabels` to use `stdin` instead of the input file. I would also use `respondSource` instead of `sendFile` delete the temporary output file using `addCleanUp`. I would also for reason I don't remember, try to read stderr (and close in the cleanUp other glabels will stop before finishing).

    generateLabelsResponse ::
    Text
    -> Text
    -> Conduit () (HandlerT site IO) Text
    -> HandlerT site IO TypedContent
    generateLabelsResponse outputName template labelSource = do
      -- let types = (outputName, template) :: (Text, Text)
      (tmp, thandle) <- liftIO $ openTempFile "/tmp/DocumentCache" (unpack outputName)
      (pin, Inherited, perr, phandle ) <- streamingProcess (proc "glabels-3-batch"
                                                            ["--input=-"
                                                            , "--output"
                                                            , tmp
                                                            , (unpack template)
                                                            ]
                                                      ) {env = Just [("LANG", "C.UTF-8")]}
      runConduit $ labelSource =$= encodeUtf8C =$= sinkHandle pin
      liftIO $ hClose pin
      _exitCode <- waitForStreamingProcess phandle
      -- we would like to check the exitCode, unfortunately
      -- glabels doesn't set the exit code.
      -- we need to stderr instead 
      errorMessage <- sourceToList  $ sourceHandle perr 
      let cleanUp = liftIO $  do
            hClose perr

            removeFile tmp
            hClose thandle

      case errorMessage of
        _ ->  do
          setAttachment (fromStrict outputName)
          respondSource "application/pdf"
                        (const cleanUp `addCleanup` CB.sourceHandle thandle =$= mapC (toFlushBuilder))

If I just remove the `addCleanUp` from code below. I get an empty file.

**Comment by snoyberg** [comment]
I don't know why the code may have worked previously, but I can understand what's happening now. By using `withAcquire`, you're ensuring that when the scope of that function call ends, the file will be deleted. That's explicitly _not_ what you want, since you want to let the file live until after Warp can send the response. Try using `allocateAcquire` instead.

**Comment by maxigit** [comment]
`allocateAcquire` work indeed ! Thank you very much.
I didn't realize that there was a difference between `allocatAcquire` and `withAcquire`. In fact, I didn't realize that `allocateAcquire` would deallocate automatically. I thought I add to do it manually somewhere, and as I couldn't find it, thought `withAcquire` was the way to do.
It makes totally sense now. I think it worked before , because `addCleanUp` would be executed at the of the response conduit, i.e, after Warp finished consuming the response.

Again, thank you really much. It might be worth documenting somewhere that using `sendFile` on a file creating with `withTempFile` doesn't work but need to be created and removed using `allocateAcquire` instead.

**Comment by maxigit** [comment]
I just read the example in `Reproducible Stack Code Snippet` in the documentation of `Data.Acquire` and what is confusing is the use of `release` which is if I understand well, only optionnal. It does however, suggest that `release` needs to be called explicitely.
