### ISSUE TITLE
Doesn't work with GHC 7.10

### ISSUE THREAD

**Issue by ndmitchell** [snoyberg/conduit#354]
See https://travis-ci.org/ndmitchell/hoogle/jobs/348230688. The build matrix complains it doesn't build anywhere, but I suspect that isn't true.

**Comment by snoyberg** [comment]
The latest version explicitly has a lower bound. I'm going to need to ask
you to provide more thorough descriptions here please, the last few issues
you've filed about build matrix stuff has required far more of my time to
understand than I can continue to invest.

**Comment by ndmitchell** [comment]
I see the build matrix has changed beyond recognition since I first reported. It seems in my build plan for 7.10 it is picking conduit-extra-1.2.3.1 with streaming-0.2.0.0. Presumably it picked 1.2.3.1 over 1.2.3.2 because it really wanted to get a higher streaming to go with it. I added a >= 1.2.3.2 constraint which forces Cabal down a sensible path and that seemed to work.

Sorry it's taking so long to sort these things - it seems that you dropping GHC version support faster than me is probably at the root cause. It would be nice if the community had a generally accepted view on this (hvr is clearly going for back to 7.4 while you're back to 8.0 - quite a difference).

**Comment by snoyberg** [comment]
The generally accepted policy has been three major versions. With 8.4
coming out imminently, I jumped the gun a bit in order to significantly
simplify some things.

**Comment by hvr** [comment]
@ndmitchell For some more foundational packages I even try to support back till GHC 7.0.4 because that's what I can reasonably CI via Travis, unless it's too much effort. But as soon as I rely on Generics, GHC 7.4 is usually the lower bound (also because GHC 7.4 is the oldest GHC I can currently test on Windows via Appveyor). The next natural boundary is GHC 7.10.3 due to AMP.
